"""Where a controlled execution was created."""

EXECUTION_SOURCE_USER = "user"
EXECUTION_SOURCE_AI_RESEARCH = "ai_research"
EXECUTION_SOURCE_AI_CHATBOT_PANEL = "ai_chatbot_panel"
EXECUTION_SOURCE_CHART_OPPORTUNITY = "chart_opportunity_auto"
EXECUTION_SOURCE_MOMENTUM_TRADE = "momentum-trade"

VALID_EXECUTION_SOURCES = frozenset(
    {
        EXECUTION_SOURCE_USER,
        EXECUTION_SOURCE_AI_RESEARCH,
        EXECUTION_SOURCE_AI_CHATBOT_PANEL,
        EXECUTION_SOURCE_CHART_OPPORTUNITY,
        EXECUTION_SOURCE_MOMENTUM_TRADE,
    }
)

EXECUTION_SOURCE_LABELS = {
    EXECUTION_SOURCE_USER: "User",
    EXECUTION_SOURCE_AI_RESEARCH: "AI Research",
    EXECUTION_SOURCE_AI_CHATBOT_PANEL: "AI Chatbot",
    EXECUTION_SOURCE_CHART_OPPORTUNITY: "Chart scan",
    EXECUTION_SOURCE_MOMENTUM_TRADE: "Momentum",
}

DEFAULT_EXECUTION_SOURCE = EXECUTION_SOURCE_USER
